'use strict';
export const FETCH_ADDRESS_DATA = 'FETCH_ADDRESS_DATA';
export const FETCH_ADDRESS_DATA_SUCCEEDED = 'FETCH_ADDRESS_DATA_SUCCEEDED';
export const FETCH_ADDRESS_DATA_FAILED = 'FETCH_ADDRESS_DATA_FAILED';
export const CLEAR_ADDRESS_DATA = 'CLEAR_ADDRESS_DATA';
export const SET_USERNAME = 'SET_USERNAME';


export const SEND_COIN = 'SEND_COIN';
export const SEND_COIN_SUCCEEDED = 'SEND_COIN_SUCCEEDED';
export const SEND_COIN_FAILED = 'SEND_COIN_FAILED';
export const CLEAR_SEND_COIN = 'CLEAR_SEND_COIN';


export const LOGOUT_PRESSED = 'LOGOUT_PRESSED';
export const CLEAR_DATA = 'CLEAR_DATA';
